// generated by nodegen.py; do not edit

#pragma once

struct Invalid;
struct NumberLiteral;
struct StringLiteral;
struct BooleanLiteral;
struct Identifier;
struct FunctionCall;
struct InfixOperator;
struct PrefixOperator;
struct PostfixOperator;
struct Block;
struct Program;
struct VariableDef;

class Visitor
{
public:
	virtual void visit(Invalid &node) = 0;
	virtual void visit(NumberLiteral &node) = 0;
	virtual void visit(StringLiteral &node) = 0;
	virtual void visit(BooleanLiteral &node) = 0;
	virtual void visit(Identifier &node) = 0;
	virtual void visit(FunctionCall &node) = 0;
	virtual void visit(InfixOperator &node) = 0;
	virtual void visit(PrefixOperator &node) = 0;
	virtual void visit(PostfixOperator &node) = 0;
	virtual void visit(Block &node) = 0;
	virtual void visit(Program &node) = 0;
	virtual void visit(VariableDef &node) = 0;
};
